import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { readActiveQueue, readDoneQueue, markQueueItemDone, archiveDoneItems } from '../../queue-store.mjs';
import { getDomainAdapter } from '../../domains/index.mjs';
import { createOutputContract, validateLocalOutput } from '../../validators/output-validator.mjs';
import { collectCodexThreadUsage, enrichTokenCounter } from '../../usage-telemetry.mjs';

const id = 'company-investment-decision-CC-2026-09-08T22_52_16-07_00-aef3039ce3';
const threadId = '01a086fb-2560-7f02-bdd8-c3da150bc8a3';
const sessionPath = 'C:/Users/cheny/.codex/sessions/2026/09/09/rollout-2026-09-09T09-23-21-01a086fb-2560-7f02-bdd8-c3da150bc8a3.jsonl';
assert.equal(fs.existsSync(new URL('../../runner.lock', import.meta.url)), false);
const before = readActiveQueue();
const item = before.find(x => x.id === id);
assert.equal(item?.status, 'running');
assert.equal(before.filter(x => x.status === 'running').length, 1);
assert.equal(readDoneQueue().some(x => x.id === id), false);
const events = fs.readFileSync(sessionPath, 'utf8').trim().split(/\r?\n/).map(JSON.parse);
assert.equal(events[0].payload.id, threadId);
const terminal = events.at(-1);
assert.equal(terminal.payload.type, 'task_complete');
assert.equal(terminal.payload.turn_id, '01a086fb-2637-78e3-96b0-614fa631f756');
assert.ok(!terminal.payload.error && terminal.payload.last_agent_message);
const adapter = getDomainAdapter(item.domain);
const outputFile = validateLocalOutput(item, adapter, createOutputContract(item, adapter));
const outputPath = 'D:/drive/Investment/' + outputFile;
const sha = () => crypto.createHash('sha256').update(fs.readFileSync(outputPath)).digest('hex');
assert.equal(sha(), '86a29f24c6f3297d64f67a64bca212f47421c735f4c0d69eb10ffee27d76ccb1');
const aggregate = collectCodexThreadUsage(threadId);
assert.ok(aggregate.counters && aggregate.unresolvedThreadCount === 0);
const metadata = { includesSubagents: aggregate.subagentThreadCount > 0, threadCount: aggregate.threadCount, subagentThreadCount: aggregate.subagentThreadCount, unresolvedThreadCount: aggregate.unresolvedThreadCount };
const formal = enrichTokenCounter(aggregate.counters, { model: 'gpt-6-astra', reasoningEffort: item.reasoningEffort, threadId, usageSource: aggregate.usageSource, ...metadata });
const total = enrichTokenCounter(aggregate.counters, { ...metadata, usageAggregation: 'parent_plus_subagents' });
markQueueItemDone(id, { outputFile, note: 'codex_sdk_done_recovered: successful session; SDK remained pending after timeout; runner stopped and output validated', tokenUsageAttempt: { attempt: item.attempts, formal, total, ...metadata, usageAggregation: 'parent_plus_subagents' } });
const archived = archiveDoneItems();
assert.equal(archived.archived, 1);
assert.deepEqual(readActiveQueue(), before.filter(x => x.id !== id));
const done = readDoneQueue().filter(x => x.id === id);
assert.equal(done.length, 1);
assert.equal(done[0].status, 'done');
assert.equal(sha(), '86a29f24c6f3297d64f67a64bca212f47421c735f4c0d69eb10ffee27d76ccb1');
const audit = { timestamp: new Date().toISOString(), event: 'Recovered CC after authorized runner shutdown.', id, threadId, sessionCompletedAt: terminal.timestamp, outputFile, outputSha256: sha(), outputTokens: formal.outputTokens, archivedDoneItems: 1, otherActiveItemsUnchanged: true };
fs.writeFileSync(new URL('./recovery-result.json', import.meta.url), JSON.stringify(audit, null, 2) + '\n');
fs.appendFileSync(new URL('../../logs/current.jsonl', import.meta.url), JSON.stringify(audit) + '\n');
console.log(JSON.stringify(audit, null, 2));
