import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { QUEUE_PATH,DONE_QUEUE_PATH,writeActiveQueue } from '../../tools/research-runner/queue-store.mjs';
const receipt=JSON.parse(fs.readFileSync(new URL('16份方案入队回执.json',import.meta.url),'utf8'));
const removeIds=new Set(receipt.items.filter(x=>x.variant==='ABCDE').map(x=>x.queue_id));
const keepIds=new Set(receipt.items.filter(x=>x.variant==='BCDE').map(x=>x.queue_id));
assert.equal(removeIds.size,13);assert.equal(keepIds.size,3);
const raw=fs.readFileSync(QUEUE_PATH,'utf8');
const rows=raw.split(/\r?\n/).filter(x=>x.trim()).map(x=>JSON.parse(x));
const removed=rows.filter(x=>removeIds.has(x.id));
assert.equal(removed.length,13);
assert.ok(removed.every(x=>x.status==='pending'),'Dependent sorting already started; do not remove a running task');
const kept=rows.filter(x=>keepIds.has(x.id));assert.equal(kept.length,3);
const stamp=new Date().toISOString().replace(/[:.]/g,'-');
const backup=path.join('D:/drive/Investment/tools/research-runner/queue-backups',`retain-bcde-${stamp}`);
fs.mkdirSync(backup,{recursive:true});
fs.writeFileSync(path.join(backup,'queue.jsonl'),raw,'utf8');
fs.copyFileSync(DONE_QUEUE_PATH,path.join(backup,'queue.done.jsonl'));
fs.writeFileSync(path.join(backup,'withdrawn-13.json'),JSON.stringify(removed,null,2),'utf8');
assert.equal(fs.readFileSync(QUEUE_PATH,'utf8'),raw,'Queue changed during preparation; re-read before changing it');
const expected=rows.filter(x=>!removeIds.has(x.id));
writeActiveQueue(expected);
const after=fs.readFileSync(QUEUE_PATH,'utf8').split(/\r?\n/).filter(x=>x.trim()).map(x=>JSON.parse(x));
assert.ok(!after.some(x=>removeIds.has(x.id)));
assert.equal(after.filter(x=>keepIds.has(x.id)).length,3);
for(const old of expected){const now=after.find(x=>x.id===old.id);assert.ok(now);assert.deepEqual(now,old);}
const result={removed:removed.length,retained:kept.map(x=>({id:x.id,name:x.displayName,status:x.status})),activeQueueCount:after.length,otherTasksPreserved:expected.length-kept.length,backup};
fs.writeFileSync(new URL('仅保留BCDE入队回执.json',import.meta.url),JSON.stringify(result,null,2),'utf8');
console.log(JSON.stringify(result,null,2));
